// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH6981LgTSJmI5j6mZAcRzufTM6ughpPk',
    appId: '1:1096660476559:web:d547fa8434854ab66486fa',
    messagingSenderId: '1096660476559',
    projectId: 'warteg-uts',
    authDomain: 'warteg-uts.firebaseapp.com',
    storageBucket: 'warteg-uts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTODT_TJVH6b1B-lED24zXzAzK5Oc7QY',
    appId: '1:1096660476559:android:5e8bdebf258649c36486fa',
    messagingSenderId: '1096660476559',
    projectId: 'warteg-uts',
    storageBucket: 'warteg-uts.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH6981LgTSJmI5j6mZAcRzufTM6ughpPk',
    appId: '1:1096660476559:web:0cfbcce4347777766486fa',
    messagingSenderId: '1096660476559',
    projectId: 'warteg-uts',
    authDomain: 'warteg-uts.firebaseapp.com',
    storageBucket: 'warteg-uts.firebasestorage.app',
  );
}
